### ISSUE TITLE
jQuery plugin Youtube HD Thumbnails cannot be loaded

### ISSUE THREAD

**Issue by lukasgabriel** [demokratie-live/democracy-website#56]
#55  adds a plugin that forces the YT iframe to use the maximum quality for video thumbnails (commit 5d706c5)

It works by replacing the `hqdefault` with `maxresdefault` in the automatically loaded `background-img` property of the iframe.

On page load, the following edxception is thrown:
`Uncaught TypeError: $(...).youTubeHDThumbnail is not a function`

The plugin is included in \democracy\files\YouTubeHDThumbnail\ as specified in https://github.com/simonlidesign/YouTubeHDThumbnail 

I since removed the `class="yt-hd-thumbnail"` from the video; when fixing the issue, it has to be re-added to the iframe according to the [README](https://github.com/simonlidesign/YouTubeHDThumbnail).

**Comment by ManAnRuck** [comment]
Ich glaub das fällt unter "It's not a bug, it's a feature" :/

Die PHP Infrastruktur ist wohl so konfiguriert, dass Dateien unter /files nicht direkt erreichbar sind. Wie's konfiguriert werden muss um dies zu lösen kann ich dir leider nicht sagen. 

Es scheint irgendwas über eine im cache generierte JS Datei ausgespielt zu werden.

<img width="948" alt="Bildschirmfoto 2021-08-08 um 09 50 27" src="https://user-images.githubusercontent.com/2183135/128625001-b4a6deb2-a4d8-4d70-a754-61f50e33fc2b.png">
<img width="595" alt="Bildschirmfoto 2021-08-08 um 09 50 42" src="https://user-images.githubusercontent.com/2183135/128625005-6d43269a-a33d-408c-b961-0b0173a1760d.png">



Alternative wäre das plugin über ein CDN zu laden.

**Comment by visionmakery** [comment]
@lukasgabriel Du hattest doch eine Alternativ-Lösung durch einen kleines jS-Script á la Video-"Klasse" von X zu Y ändern, oder?

**Comment by lukasgabriel** [comment]
@ManAnRuck der Teil des Plugins, der das thumbnail tauscht, ist AFAIK nur ein paar Zeilen. Könnten wir das nicht auch in die default_home.js/default_about.js reinkopieren, oder inline,

@visionmakery Wir könnten auch selbst eine kleine Funktion schreiben, die einfach den website body (oder besser: nur die Video iFrame Klasse) NACH dem Laden durchsucht und den String hqdefault durch maxresdefault ersetzt. Aber das sollte jemand tun, der ein wenig kompetenter mit JS umgehen kann als ich :)

**Comment by lukasgabriel** [comment]
Was not closed in #55
