### ISSUE TITLE
🐛[Website] Typo "das Wahl-O-Meter"

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-website#59]
<img width="1019" alt="Bildschirmfoto 2021-08-30 um 14 27 17" src="https://user-images.githubusercontent.com/32302889/131338860-7e6d773b-f15a-49c4-a1b8-2cb8437a547b.png">
hier müsste "der Wahl-O-Meter" stehen!

**Comment by lukasgabriel** [comment]
Solved by #58
