### ISSUE TITLE
🖥 [Website] Instagram fehlt im Footer

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-website#70]
- [ ] Instagram-Icon hinzufügen
<img width="1183" alt="Bildschirmfoto 2021-05-14 um 14 56 32" src="https://user-images.githubusercontent.com/32302889/118273773-a2a14600-b4c4-11eb-8ffb-fd749894e38d.png">

- [ ] auf "CC BY NC ND 4.0 — 202**1** DEMOCRACY Deutschland e.V." ändern

**Comment by ManAnRuck** [comment]
oh it's already implemented 🚀

**Comment by visionmakery** [comment]
Ist er wirklich schon implementiert? Der hängt so geschmacklos in der Mitte wegen eines Workarounds von Lukas...
